function [ output_features ] = histopath_features( input_regions, input_image )
%HISTOPATH_FEATURES
%   Given the whitespace/cytoplasm/nuclei regions of a histopathology
%   image, this function extracts the corresponding features.

if (length(input_regions) ~= 3)
    error('Input regions must be a 3-cell array of the connected components of each class (whitespace/cytoplasm/nuclei)');
end

whitespace_regions = input_regions{1};
cytoplasm_regions  = input_regions{2};
nuclei_regions     = input_regions{3};

[M, N, ~] = size(input_image);

if ((M ~= whitespace_regions.ImageSize(1)) || ...
    (N ~= whitespace_regions.ImageSize(2)))
    error('Input image size must match total size of regions');
end

if ((M ~= cytoplasm_regions.ImageSize(1)) || ...
    (N ~= cytoplasm_regions.ImageSize(2)))
    error('Input image size must match total size of regions');
end

if ((M ~= nuclei_regions.ImageSize(1)) || ...
    (N ~= nuclei_regions.ImageSize(2)))
    error('Input image size must match total size of regions');
end

nuclei_region_stats = regionprops(nuclei_regions, ...
                                  'Centroid', ...
                                  'Area', ...
                                  'MajorAxisLength', ...
                                  'MinorAxisLength', ...
                                  'EquivDiameter', ...
                                  'Orientation', ...
                                  'Perimeter', ...
                                  'Solidity');

nuclei_region_indices = 1:length(nuclei_region_stats); % zeros(0, 1);

% for i = 1:length(nuclei_region_stats)
%    % Only extract features from regions larger than 9 pixels;
%    % this ensures that small regions that contain very little information
%    % are ignored
%    if (nuclei_region_stats(i).Area >= 5)
%        nuclei_region_indices = [nuclei_region_indices; i];
%    end
% end

if (isempty(nuclei_region_indices))
    warning('No nuclei regions to extract features from!');
end

centroids        = zeros(length(nuclei_region_indices), 2);
areas            = zeros(length(nuclei_region_indices), 1);
majoraxislengths = zeros(length(nuclei_region_indices), 1);
minoraxislengths = zeros(length(nuclei_region_indices), 1);
equivdiameters   = zeros(length(nuclei_region_indices), 1);
eccentricity     = zeros(length(nuclei_region_indices), 1);
orientation      = zeros(length(nuclei_region_indices), 1);
perimeters       = zeros(length(nuclei_region_indices), 1);
solidity         = zeros(length(nuclei_region_indices), 1);
compactness      = zeros(length(nuclei_region_indices), 1);
crowdedness      = zeros(length(nuclei_region_indices), 1);
alignedness      = zeros(length(nuclei_region_indices), 1);
neighbordistmin  = zeros(length(nuclei_region_indices), 1);
neighbordistmax  = zeros(length(nuclei_region_indices), 1);
neighbordistavg  = zeros(length(nuclei_region_indices), 1);
neighbordiststd  = zeros(length(nuclei_region_indices), 1);
nma_nbrdistmin   = zeros(length(nuclei_region_indices), 1);
nma_nbrdistmax   = zeros(length(nuclei_region_indices), 1);
nma_nbrdistavg   = zeros(length(nuclei_region_indices), 1);
nma_nbrdiststd   = zeros(length(nuclei_region_indices), 1);
ned_nbrdistmin   = zeros(length(nuclei_region_indices), 1);
ned_nbrdistmax   = zeros(length(nuclei_region_indices), 1);
ned_nbrdistavg   = zeros(length(nuclei_region_indices), 1);
ned_nbrdiststd   = zeros(length(nuclei_region_indices), 1);
nucleicoloravg   = zeros(length(nuclei_region_indices), 3);
nucleicolorstdev = zeros(length(nuclei_region_indices), 3);
nucleigrayavg    = zeros(length(nuclei_region_indices), 1);
nucleigraystdev  = zeros(length(nuclei_region_indices), 1);

if (~isempty(nuclei_region_indices))
    for i = 1:length(nuclei_region_indices)
        centroids(i, :)     = nuclei_region_stats(nuclei_region_indices(i)).Centroid;
        areas(i)            = nuclei_region_stats(nuclei_region_indices(i)).Area;
        majoraxislengths(i) = nuclei_region_stats(nuclei_region_indices(i)).MajorAxisLength;
        minoraxislengths(i) = nuclei_region_stats(nuclei_region_indices(i)).MinorAxisLength;
        equivdiameters(i)   = nuclei_region_stats(nuclei_region_indices(i)).EquivDiameter;
        % Get eccentricity as "second flattening";
        % "second flattening" is used because it is linear in the major axis
        % which provides a more intuitive way to calculate the "alignedness"
        eccentricity(i)     = (majoraxislengths(i) - minoraxislengths(i)) ./ ...
                              minoraxislengths(i);
        % Get orientation in radians from 0 to pi
        orientation(i)      = (pi / 180) * ...
                              nuclei_region_stats(nuclei_region_indices(i)).Orientation;
        orientation(i)      = (orientation(i) >= 0) .*  orientation(i) + ...
                              (orientation(i) <  0) .* (orientation(i) + pi);
        perimeters(i)       = nuclei_region_stats(nuclei_region_indices(i)).Perimeter;
        solidity(i)         = 1 ./ nuclei_region_stats(nuclei_region_indices(i)).Solidity;
    end

    compactness = (perimeters .^ 2) ./ (4 * pi * areas);

    [voronoi_vertices, voronoi_cells] = voronoin(centroids);

    for i = 1:length(nuclei_region_indices)
        voronoi_vertices_i = zeros(0, 2);
        for j = 1:length(voronoi_cells{i})
            if (any(isinf(voronoi_vertices(voronoi_cells{i}(j), :))))
                crowdedness(i) = NaN;
                break;
            end
            voronoi_vertices_i = [voronoi_vertices_i; ...
                                  voronoi_vertices(voronoi_cells{i}(j), :)];
        end
        if (isnan(crowdedness(i)) || ...
            (size(voronoi_vertices_i, 1) < 3) || ...
            (any(voronoi_vertices_i(:, 1) > M)) || ...
            (any(voronoi_vertices_i(:, 1) < 1)) || ...
            (any(voronoi_vertices_i(:, 2) > N)) || ...
            (any(voronoi_vertices_i(:, 2) < 1)))
            % Crowdedness is undefined for voronoi partitions
            % that are not completely enclosed in the image
            crowdedness(i) = NaN;
        else
            [~, voronoi_area] = convhulln(voronoi_vertices_i);
            crowdedness(i) = voronoi_area ./ areas(i);
        end
    end

    triangulation = delaunayTriangulation(centroids);

    for i = 1:length(nuclei_region_indices)
        neighbors_i = isConnected(triangulation, ...
                                  i .* ones(length(nuclei_region_indices), 1), ...
                                  (1:length(nuclei_region_indices))');
        if (sum(neighbors_i) <= 0)
            neighbordistmin(i) = NaN;
            neighbordistmax(i) = NaN;
            neighbordistavg(i) = NaN;
            neighbordiststd(i) = NaN;

            nma_nbrdistmin(i) = NaN;
            nma_nbrdistmax(i) = NaN;
            nma_nbrdistavg(i) = NaN;
            nma_nbrdiststd(i) = NaN;

            ned_nbrdistmin(i) = NaN;
            ned_nbrdistmax(i) = NaN;
            ned_nbrdistavg(i) = NaN;
            ned_nbrdiststd(i) = NaN;

            alignedness(i) = NaN;
        else
            neighbors_i_distance = sqrt((centroids(i, 1) - ...
                                         centroids(neighbors_i, 1)).^2 + ...
                                        (centroids(i, 2) - ...
                                         centroids(neighbors_i, 2)).^2);

            neighbors_i_distance_nma = neighbors_i_distance ./ ...
                                       mean(majoraxislengths, 'omitnan');

            neighbors_i_distance_ned = neighbors_i_distance ./ ...
                                       mean(equivdiameters, 'omitnan');

            neighbordistmin(i) = min(neighbors_i_distance, [], 1, 'omitnan');
            neighbordistmax(i) = max(neighbors_i_distance, [], 1, 'omitnan');
            neighbordistavg(i) = mean(neighbors_i_distance, 'omitnan');
            neighbordiststd(i) = std(neighbors_i_distance, 'omitnan');

            nma_nbrdistmin(i) = min(neighbors_i_distance_nma, [], 1, 'omitnan');
            nma_nbrdistmax(i) = max(neighbors_i_distance_nma, [], 1, 'omitnan');
            nma_nbrdistavg(i) = mean(neighbors_i_distance_nma, 'omitnan');
            nma_nbrdiststd(i) = std(neighbors_i_distance_nma, 'omitnan');

            ned_nbrdistmin(i) = min(neighbors_i_distance_ned, [], 1, 'omitnan');
            ned_nbrdistmax(i) = max(neighbors_i_distance_ned, [], 1, 'omitnan');
            ned_nbrdistavg(i) = mean(neighbors_i_distance_ned, 'omitnan');
            ned_nbrdiststd(i) = std(neighbors_i_distance_ned, 'omitnan');

            neighbors_i_eccentricity = eccentricity(neighbors_i);
            neighbors_i_orientation  = orientation(neighbors_i);

            alignedness(i) = calculate_alignedness([eccentricity(i), ...
                                                    orientation(i)], ...
                                                   [neighbors_i_eccentricity, ...
                                                    neighbors_i_orientation]);
        end
    end

    for i = 1:length(nuclei_region_indices)
        [k, l] = ind2sub([M, N], nuclei_regions.PixelIdxList{nuclei_region_indices(i)});
        regionpixels = zeros(length(k), size(input_image, 3));
        for j = 1:length(k)
            regionpixels(j, :) = double(input_image(k(j), l(j), :));
        end
        if (size(regionpixels, 2) ~= 3)
            % Ensure exactly three channels
            regionpixels = [regionpixels(:, 1), ...
                            regionpixels(:, 2), ...
                            regionpixels(:, 3)];
        end
        nucleicoloravg(i, 1) = mean(regionpixels(:, 1), 'omitnan');
        nucleicoloravg(i, 2) = mean(regionpixels(:, 2), 'omitnan');
        nucleicoloravg(i, 3) = mean(regionpixels(:, 3), 'omitnan');
        nucleicolorstdev(i, 1) = std(regionpixels(:, 1), 'omitnan');
        nucleicolorstdev(i, 2) = std(regionpixels(:, 2), 'omitnan');
        nucleicolorstdev(i, 3) = std(regionpixels(:, 3), 'omitnan');
        nucleigrayavg(i) = mean((regionpixels(:, 1) + ...
                                 regionpixels(:, 2) + ...
                                 regionpixels(:, 3)) ./ 3, ...
                                 'omitnan');
        nucleigraystdev(i) = std((regionpixels(:, 1) + ...
                                  regionpixels(:, 2) + ...
                                  regionpixels(:, 3)) ./ 3, ...
                                  'omitnan');
    end
end

nuclei_mask = false(M, N);

for i = 1:length(nuclei_regions.PixelIdxList)
    nuclei_mask(nuclei_regions.PixelIdxList{i}) = true;
end
         
cytoplasm_mask = false(M, N);

for i = 1:length(cytoplasm_regions.PixelIdxList)
    cytoplasm_mask(cytoplasm_regions.PixelIdxList{i}) = true;
end

whitespace_mask = and(~nuclei_mask, ~cytoplasm_mask);

% Distance transforms
% (for each pixel within, the distance to the nearest region boundary)
cytoplasm_dist_transform = bwdist(~cytoplasm_mask);

nma_cytoplasm_dist_transform = cytoplasm_dist_transform ./ ...
                               mean(majoraxislengths, 'omitnan');

ned_cytoplasm_dist_transform = cytoplasm_dist_transform ./ ...
                               mean(equivdiameters, 'omitnan');

nucl_cyto_dist_transform = bwdist(whitespace_mask); % Nuclei + cytoplasm

nma_nucl_cyto_dist_transform = nucl_cyto_dist_transform ./ ...
                               mean(majoraxislengths, 'omitnan');

ned_nucl_cyto_dist_transform = nucl_cyto_dist_transform ./ ...
                               mean(equivdiameters, 'omitnan');
                           
whitespace_dist_transform = bwdist(~whitespace_mask);

nma_whitespace_dist_transform = whitespace_dist_transform ./ ...
                                mean(majoraxislengths, 'omitnan');

ned_whitespace_dist_transform = whitespace_dist_transform ./ ...
                                mean(equivdiameters, 'omitnan');

% Gray level co-occurence matrix features
redimage   = double(input_image(:, :, 1));
greenimage = double(input_image(:, :, 2));
blueimage  = double(input_image(:, :, 3));

grayimage = (redimage + ...
             greenimage + ...
             blueimage) ./ 3;
         
nuclei_glcm_features     = haralick_features(grayimage, nuclei_mask);
cytoplasm_glcm_features  = haralick_features(grayimage, cytoplasm_mask);
whitespace_glcm_features = haralick_features(grayimage, whitespace_mask);

% Use the reciprocal of the first two GLCM features
% since they are bounded between [0,1] and
% typically end up being very close to zero;
% take the square root of the first and third
% GLCM features since they are the sum of squared terms
% and would otherwise account for orders of magnitude
% more variance than the other features
nuclei_glcm_features(1)     = 1 ./ sqrt(nuclei_glcm_features(1));
nuclei_glcm_features(2)     = 1 ./ nuclei_glcm_features(2);
nuclei_glcm_features(3)     = sqrt(nuclei_glcm_features(3));
cytoplasm_glcm_features(1)  = 1 ./ sqrt(cytoplasm_glcm_features(1));
cytoplasm_glcm_features(2)  = 1 ./ cytoplasm_glcm_features(2);
cytoplasm_glcm_features(3)  = sqrt(cytoplasm_glcm_features(3));
whitespace_glcm_features(1) = 1 ./ sqrt(whitespace_glcm_features(1));
whitespace_glcm_features(2) = 1 ./ whitespace_glcm_features(2);
whitespace_glcm_features(3) = sqrt(whitespace_glcm_features(3));

features = [distribution_parameters(areas), ...
            distribution_parameters(majoraxislengths), ...
            distribution_parameters(equivdiameters), ...
            distribution_parameters(eccentricity), ...
            distribution_parameters(solidity), ...
            distribution_parameters(compactness), ...
            distribution_parameters(crowdedness), ...
            distribution_parameters(alignedness), ...
            distribution_parameters(neighbordistmin), ...
            distribution_parameters(neighbordistmax), ...
            distribution_parameters(neighbordistavg), ...
            distribution_parameters(neighbordiststd), ...
            distribution_parameters(nma_nbrdistmin), ...
            distribution_parameters(nma_nbrdistmax), ...
            distribution_parameters(nma_nbrdistavg), ...
            distribution_parameters(nma_nbrdiststd), ...
            distribution_parameters(ned_nbrdistmin), ...
            distribution_parameters(ned_nbrdistmax), ...
            distribution_parameters(ned_nbrdistavg), ...
            distribution_parameters(ned_nbrdiststd), ...
            distribution_parameters(nucleicoloravg(:, 1)), ...
            distribution_parameters(nucleicoloravg(:, 2)), ...
            distribution_parameters(nucleicoloravg(:, 3)), ...
            distribution_parameters(nucleicolorstdev(:, 1)), ...
            distribution_parameters(nucleicolorstdev(:, 2)), ...
            distribution_parameters(nucleicolorstdev(:, 3)), ...
            distribution_parameters(nucleigrayavg), ...
            distribution_parameters(nucleigraystdev), ...
            ... %
            distribution_parameters(redimage(cytoplasm_mask)), ...
            distribution_parameters(greenimage(cytoplasm_mask)), ...
            distribution_parameters(blueimage(cytoplasm_mask)), ...
            distribution_parameters(grayimage(cytoplasm_mask)), ...
            ... %
            distribution_parameters(cytoplasm_dist_transform(cytoplasm_mask)), ...
            distribution_parameters(nma_cytoplasm_dist_transform(cytoplasm_mask)), ...
            distribution_parameters(ned_cytoplasm_dist_transform(cytoplasm_mask)), ...
            distribution_parameters(nucl_cyto_dist_transform(~whitespace_mask)), ...
            distribution_parameters(nma_nucl_cyto_dist_transform(~whitespace_mask)), ...
            distribution_parameters(ned_nucl_cyto_dist_transform(~whitespace_mask)), ...
            distribution_parameters(whitespace_dist_transform(whitespace_mask)), ...
            distribution_parameters(nma_whitespace_dist_transform(whitespace_mask)), ...
            distribution_parameters(ned_whitespace_dist_transform(whitespace_mask)), ...
            ... %
            nuclei_glcm_features(1), ...
            nuclei_glcm_features(2), ...
            nuclei_glcm_features(3), ...
            nuclei_glcm_features(4), ...
            nuclei_glcm_features(5), ...
            nuclei_glcm_features(6), ...
            ... %
            cytoplasm_glcm_features(1), ...
            cytoplasm_glcm_features(2), ...
            cytoplasm_glcm_features(3), ...
            cytoplasm_glcm_features(4), ...
            cytoplasm_glcm_features(5), ...
            cytoplasm_glcm_features(6), ...
            ... %
            whitespace_glcm_features(1), ...
            whitespace_glcm_features(2), ...
            whitespace_glcm_features(3), ...
            whitespace_glcm_features(4), ...
            whitespace_glcm_features(5), ...
            whitespace_glcm_features(6)];

features(isnan(features)) = 0;

feature_labels = {... % Labels for features
                  'NucleiArea_Avg', ...
                  'NucleiArea_Stdev', ...
                  'NucleiArea_Median', ...
                  'NucleiArea_IQR', ...
                  'NucleiArea_Skewness', ...
                  'NucleiArea_Kurtosis', ...
                  ... %
                  'NucleiMajorAxis_Avg', ...
                  'NucleiMajorAxis_Stdev', ...
                  'NucleiMajorAxis_Median', ...
                  'NucleiMajorAxis_IQR', ...
                  'NucleiMajorAxis_Skewness', ...
                  'NucleiMajorAxis_Kurtosis', ...
                  ... % 
                  'NucleiEquivDiam_Avg', ...
                  'NucleiEquivDiam_Stdev', ...
                  'NucleiEquivDiam_Median', ...
                  'NucleiEquivDiam_IQR', ...
                  'NucleiEquivDiam_Skewness', ...
                  'NucleiEquivDiam_Kurtosis', ...
                  ... % 
                  'NucleiEccentricity_Avg', ...
                  'NucleiEccentricity_Stdev', ...
                  'NucleiEccentricity_Median', ...
                  'NucleiEccentricity_IQR', ...
                  'NucleiEccentricity_Skewness', ...
                  'NucleiEccentricity_Kurtosis', ...
                  ... % 
                  'NucleiSolidity_Avg', ...
                  'NucleiSolidity_Stdev', ...
                  'NucleiSolidity_Median', ...
                  'NucleiSolidity_IQR', ...
                  'NucleiSolidity_Skewness', ...
                  'NucleiSolidity_Kurtosis', ...
                  ... % 
                  'NucleiCompactness_Avg', ...
                  'NucleiCompactness_Stdev', ...
                  'NucleiCompactness_Median', ...
                  'NucleiCompactness_IQR', ...
                  'NucleiCompactness_Skewness', ...
                  'NucleiCompactness_Kurtosis', ...
                  ... % 
                  'NucleiCrowdedness_Avg', ...
                  'NucleiCrowdedness_Stdev', ...
                  'NucleiCrowdedness_Median', ...
                  'NucleiCrowdedness_IQR', ...
                  'NucleiCrowdedness_Skewness', ...
                  'NucleiCrowdedness_Kurtosis', ...
                  ... % 
                  'NucleiAlignedness_Avg', ...
                  'NucleiAlignedness_Stdev', ...
                  'NucleiAlignedness_Median', ...
                  'NucleiAlignedness_IQR', ...
                  'NucleiAlignedness_Skewness', ...
                  'NucleiAlignedness_Kurtosis', ...
                  ... % 
                  'NucleiNeighborDistancesMin_Avg', ...
                  'NucleiNeighborDistancesMin_Stdev', ...
                  'NucleiNeighborDistancesMin_Median', ...
                  'NucleiNeighborDistancesMin_IQR', ...
                  'NucleiNeighborDistancesMin_Skewness', ...
                  'NucleiNeighborDistancesMin_Kurtosis', ...
                  ... % 
                  'NucleiNeighborDistancesMax_Avg', ...
                  'NucleiNeighborDistancesMax_Stdev', ...
                  'NucleiNeighborDistancesMax_Median', ...
                  'NucleiNeighborDistancesMax_IQR', ...
                  'NucleiNeighborDistancesMax_Skewness', ...
                  'NucleiNeighborDistancesMax_Kurtosis', ...
                  ... % 
                  'NucleiNeighborDistancesAvg_Avg', ...
                  'NucleiNeighborDistancesAvg_Stdev', ...
                  'NucleiNeighborDistancesAvg_Median', ...
                  'NucleiNeighborDistancesAvg_IQR', ...
                  'NucleiNeighborDistancesAvg_Skewness', ...
                  'NucleiNeighborDistancesAvg_Kurtosis', ...
                  ... % 
                  'NucleiNeighborDistancesStdev_Avg', ...
                  'NucleiNeighborDistancesStdev_Stdev', ...
                  'NucleiNeighborDistancesStdev_Median', ...
                  'NucleiNeighborDistancesStdev_IQR', ...
                  'NucleiNeighborDistancesStdev_Skewness', ...
                  'NucleiNeighborDistancesStdev_Kurtosis', ...
                  ... % 
                  'NormAvgMajorAxis_NucleiNeighborDistancesMin_Avg', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesMin_Stdev', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesMin_Median', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesMin_IQR', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesMin_Skewness', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesMin_Kurtosis', ...
                  ... % 
                  'NormAvgMajorAxis_NucleiNeighborDistancesMax_Avg', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesMax_Stdev', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesMax_Median', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesMax_IQR', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesMax_Skewness', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesMax_Kurtosis', ...
                  ... % 
                  'NormAvgMajorAxis_NucleiNeighborDistancesAvg_Avg', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesAvg_Stdev', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesAvg_Median', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesAvg_IQR', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesAvg_Skewness', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesAvg_Kurtosis', ...
                  ... % 
                  'NormAvgMajorAxis_NucleiNeighborDistancesStdev_Avg', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesStdev_Stdev', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesStdev_Median', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesStdev_IQR', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesStdev_Skewness', ...
                  'NormAvgMajorAxis_NucleiNeighborDistancesStdev_Kurtosis', ...
                  ... % 
                  'NormAvgEquivDiam_NucleiNeighborDistancesMin_Avg', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesMin_Stdev', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesMin_Median', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesMin_IQR', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesMin_Skewness', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesMin_Kurtosis', ...
                  ... % 
                  'NormAvgEquivDiam_NucleiNeighborDistancesMax_Avg', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesMax_Stdev', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesMax_Median', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesMax_IQR', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesMax_Skewness', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesMax_Kurtosis', ...
                  ... % 
                  'NormAvgEquivDiam_NucleiNeighborDistancesAvg_Avg', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesAvg_Stdev', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesAvg_Median', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesAvg_IQR', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesAvg_Skewness', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesAvg_Kurtosis', ...
                  ... % 
                  'NormAvgEquivDiam_NucleiNeighborDistancesStdev_Avg', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesStdev_Stdev', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesStdev_Median', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesStdev_IQR', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesStdev_Skewness', ...
                  'NormAvgEquivDiam_NucleiNeighborDistancesStdev_Kurtosis', ...
                  ... % 
                  'NucleiRedAvg_Avg', ...
                  'NucleiRedAvg_Stdev', ...
                  'NucleiRedAvg_Median', ...
                  'NucleiRedAvg_IQR', ...
                  'NucleiRedAvg_Skewness', ...
                  'NucleiRedAvg_Kurtosis', ...
                  ... % 
                  'NucleiGreenAvg_Avg', ...
                  'NucleiGreenAvg_Stdev', ...
                  'NucleiGreenAvg_Median', ...
                  'NucleiGreenAvg_IQR', ...
                  'NucleiGreenAvg_Skewness', ...
                  'NucleiGreenAvg_Kurtosis', ...
                  ... % 
                  'NucleiBlueAvg_Avg', ...
                  'NucleiBlueAvg_Stdev', ...
                  'NucleiBlueAvg_Median', ...
                  'NucleiBlueAvg_IQR', ...
                  'NucleiBlueAvg_Skewness', ...
                  'NucleiBlueAvg_Kurtosis', ...
                  ... % 
                  'NucleiRedStdev_Avg', ...
                  'NucleiRedStdev_Stdev', ...
                  'NucleiRedStdev_Median', ...
                  'NucleiRedStdev_IQR', ...
                  'NucleiRedStdev_Skewness', ...
                  'NucleiRedStdev_Kurtosis', ...
                  ... % 
                  'NucleiGreenStdev_Avg', ...
                  'NucleiGreenStdev_Stdev', ...
                  'NucleiGreenStdev_Median', ...
                  'NucleiGreenStdev_IQR', ...
                  'NucleiGreenStdev_Skewness', ...
                  'NucleiGreenStdev_Kurtosis', ...
                  ... % 
                  'NucleiBlueStdev_Avg', ...
                  'NucleiBlueStdev_Stdev', ...
                  'NucleiBlueStdev_Median', ...
                  'NucleiBlueStdev_IQR', ...
                  'NucleiBlueStdev_Skewness', ...
                  'NucleiBlueStdev_Kurtosis', ...
                  ... % 
                  'NucleiGrayAvg_Avg', ...
                  'NucleiGrayAvg_Stdev', ...
                  'NucleiGrayAvg_Median', ...
                  'NucleiGrayAvg_IQR', ...
                  'NucleiGrayAvg_Skewness', ...
                  'NucleiGrayAvg_Kurtosis', ...
                  ... % 
                  'NucleiGrayStdev_Avg', ...
                  'NucleiGrayStdev_Stdev', ...
                  'NucleiGrayStdev_Median', ...
                  'NucleiGrayStdev_IQR', ...
                  'NucleiGrayStdev_Skewness', ...
                  'NucleiGrayStdev_Kurtosis', ...
                  ... % 
                  'CytoplasmRed_Avg', ...
                  'CytoplasmRed_Stdev', ...
                  'CytoplasmRed_Median', ...
                  'CytoplasmRed_IQR', ...
                  'CytoplasmRed_Skewness', ...
                  'CytoplasmRed_Kurtosis', ...
                  ... % 
                  'CytoplasmGreen_Avg', ...
                  'CytoplasmGreen_Stdev', ...
                  'CytoplasmGreen_Median', ...
                  'CytoplasmGreen_IQR', ...
                  'CytoplasmGreen_Skewness', ...
                  'CytoplasmGreen_Kurtosis', ...
                  ... % 
                  'CytoplasmBlue_Avg', ...
                  'CytoplasmBlue_Stdev', ...
                  'CytoplasmBlue_Median', ...
                  'CytoplasmBlue_IQR', ...
                  'CytoplasmBlue_Skewness', ...
                  'CytoplasmBlue_Kurtosis', ...
                  ... % 
                  'CytoplasmGray_Avg', ...
                  'CytoplasmGray_Stdev', ...
                  'CytoplasmGray_Median', ...
                  'CytoplasmGray_IQR', ...
                  'CytoplasmGray_Skewness', ...
                  'CytoplasmGray_Kurtosis', ...
                  ... % 
                  'CytoplasmDistanceTransform_Avg', ...
                  'CytoplasmDistanceTransform_Stdev', ...
                  'CytoplasmDistanceTransform_Median', ...
                  'CytoplasmDistanceTransform_IQR', ...
                  'CytoplasmDistanceTransform_Skewness', ...
                  'CytoplasmDistanceTransform_Kurtosis', ...
                  ... % 
                  'NormMajorAxis_CytoplasmDistanceTransform_Avg', ...
                  'NormMajorAxis_CytoplasmDistanceTransform_Stdev', ...
                  'NormMajorAxis_CytoplasmDistanceTransform_Median', ...
                  'NormMajorAxis_CytoplasmDistanceTransform_IQR', ...
                  'NormMajorAxis_CytoplasmDistanceTransform_Skewness', ...
                  'NormMajorAxis_CytoplasmDistanceTransform_Kurtosis', ...
                  ... % 
                  'NormEquivDiam_CytoplasmDistanceTransform_Avg', ...
                  'NormEquivDiam_CytoplasmDistanceTransform_Stdev', ...
                  'NormEquivDiam_CytoplasmDistanceTransform_Median', ...
                  'NormEquivDiam_CytoplasmDistanceTransform_IQR', ...
                  'NormEquivDiam_CytoplasmDistanceTransform_Skewness', ...
                  'NormEquivDiam_CytoplasmDistanceTransform_Kurtosis', ...
                  ... % 
                  'NucleiAndCytoplasmDistanceTransform_Avg', ...
                  'NucleiAndCytoplasmDistanceTransform_Stdev', ...
                  'NucleiAndCytoplasmDistanceTransform_Median', ...
                  'NucleiAndCytoplasmDistanceTransform_IQR', ...
                  'NucleiAndCytoplasmDistanceTransform_Skewness', ...
                  'NucleiAndCytoplasmDistanceTransform_Kurtosis', ...
                  ... % 
                  'NormMajorAxis_NucleiAndCytoplasmDistanceTransform_Avg', ...
                  'NormMajorAxis_NucleiAndCytoplasmDistanceTransform_Stdev', ...
                  'NormMajorAxis_NucleiAndCytoplasmDistanceTransform_Median', ...
                  'NormMajorAxis_NucleiAndCytoplasmDistanceTransform_IQR', ...
                  'NormMajorAxis_NucleiAndCytoplasmDistanceTransform_Skewness', ...
                  'NormMajorAxis_NucleiAndCytoplasmDistanceTransform_Kurtosis', ...
                  ... % 
                  'NormEquivDiam_NucleiAndCytoplasmDistanceTransform_Avg', ...
                  'NormEquivDiam_NucleiAndCytoplasmDistanceTransform_Stdev', ...
                  'NormEquivDiam_NucleiAndCytoplasmDistanceTransform_Median', ...
                  'NormEquivDiam_NucleiAndCytoplasmDistanceTransform_IQR', ...
                  'NormEquivDiam_NucleiAndCytoplasmDistanceTransform_Skewness', ...
                  'NormEquivDiam_NucleiAndCytoplasmDistanceTransform_Kurtosis', ...
                  ... % 
                  'WhitespaceDistanceTransform_Avg', ...
                  'WhitespaceDistanceTransform_Stdev', ...
                  'WhitespaceDistanceTransform_Median', ...
                  'WhitespaceDistanceTransform_IQR', ...
                  'WhitespaceDistanceTransform_Skewness', ...
                  'WhitespaceDistanceTransform_Kurtosis', ...
                  ... % 
                  'NormMajorAxis_WhitespaceDistanceTransform_Avg', ...
                  'NormMajorAxis_WhitespaceDistanceTransform_Stdev', ...
                  'NormMajorAxis_WhitespaceDistanceTransform_Median', ...
                  'NormMajorAxis_WhitespaceDistanceTransform_IQR', ...
                  'NormMajorAxis_WhitespaceDistanceTransform_Skewness', ...
                  'NormMajorAxis_WhitespaceDistanceTransform_Kurtosis', ...
                  ... % 
                  'NormEquivDiam_WhitespaceDistanceTransform_Avg', ...
                  'NormEquivDiam_WhitespaceDistanceTransform_Stdev', ...
                  'NormEquivDiam_WhitespaceDistanceTransform_Median', ...
                  'NormEquivDiam_WhitespaceDistanceTransform_IQR', ...
                  'NormEquivDiam_WhitespaceDistanceTransform_Skewness', ...
                  'NormEquivDiam_WhitespaceDistanceTransform_Kurtosis', ...
                  ... % 
                  'NucleiHaralick_AngSecMoment', ...
                  'NucleiHaralick_InvDiffMoment', ...
                  'NucleiHaralick_Contrast', ...
                  'NucleiHaralick_Correlation', ...
                  'NucleiHaralick_Entropy', ...
                  'NucleiHaralick_SumAvg', ...
                  ... % 
                  'CytoplasmHaralick_AngSecMoment', ...
                  'CytoplasmHaralick_InvDiffMoment', ...
                  'CytoplasmHaralick_Contrast', ...
                  'CytoplasmHaralick_Correlation', ...
                  'CytoplasmHaralick_Entropy', ...
                  'CytoplasmHaralick_SumAvg', ...
                  ... % 
                  'WhitespaceHaralick_AngSecMoment', ...
                  'WhitespaceHaralick_InvDiffMoment', ...
                  'WhitespaceHaralick_Contrast', ...
                  'WhitespaceHaralick_Correlation', ...
                  'WhitespaceHaralick_Entropy', ...
                  'WhitespaceHaralick_SumAvg'};

output_features = {features, feature_labels};

end